In [1]:
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime
import sklearn
import time
pd.options.display.max_rows=50
%matplotlib inline

###Carregando os dados

In [2]:
now=datetime.now()
now

datetime.datetime(2020, 12, 22, 13, 14, 53, 428588)

In [4]:
razao=pd.DataFrame(pd.read_excel('C:/Users/User/Desktop/Fabiana Contractor/CMA e Iguatemi/CMA/Forncedor 2018 CMA.xlsx'))

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/User/Desktop/Fabiana Contractor/CMA e Iguatemi/CMA/Forncedor 2018 CMA.xlsx'

In [19]:
razao['Débito']=pd.to_numeric(razao['Débito'],errors='coerce')
razao['Crédito']=pd.to_numeric(razao['Crédito'],errors='coerce')
razao['Saldo']=pd.to_numeric(razao['Saldo'],errors='coerce')
razao['Data']=str(razao['Data'])
#razao['Data']=datetime.strptime(razao['Data'],'%Y-%m-%d')
razao

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Data</th>
      <th>Histórico</th>
      <th>Débito</th>
      <th>Crédito</th>
      <th>Saldo</th>
      <th>Unnamed: 5</th>
      <th>Titulo</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>VR REF.LANÇAMENTO PARA MELHOR CLASSIFICAÇÃO</td>
      <td>NaN</td>
      <td>3000.00</td>
      <td>3115.55</td>
      <td>C</td>
      <td>AMENT</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>PAGAMENTO NF.697 RESTAURANTE PRAIA DO SUA LTDA ME</td>
      <td>265.05</td>
      <td>NaN</td>
      <td>2850.50</td>
      <td>C</td>
      <td>F.697</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>NOTA FISCAL 18837 CHEIM JORDE E ABELHA RODRIGU...</td>
      <td>NaN</td>
      <td>2815.50</td>
      <td>5666.00</td>
      <td>C</td>
      <td>1883</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>PAGAMENTO NF.16271 AMPEMES MEDICINA DO TRABALH...</td>
      <td>35.00</td>
      <td>NaN</td>
      <td>5631.00</td>
      <td>C</td>
      <td>F.162</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>PAGAMENTO NF.18673 CHEIM JORGE E ABELHA ADVOGA...</td>
      <td>2815.50</td>
      <td>NaN</td>
      <td>2815.50</td>
      <td>C</td>
      <td>F.186</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>NOTA FISCAL 707 RESTAURANTE PRAIA DO SUA LTDA</td>
      <td>NaN</td>
      <td>304.82</td>
      <td>3120.32</td>
      <td>C</td>
      <td>707</td>
    </tr>
    <tr>
      <th>6</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>PAGAMENTO NF.707 RESTAURANTE PRAIA DO SUA LTDA</td>
      <td>304.82</td>
      <td>NaN</td>
      <td>2815.50</td>
      <td>C</td>
      <td>F.707</td>
    </tr>
    <tr>
      <th>7</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>NOTA FISCAL 19032 CHEIM JORGE E ABELHA RODRIGU...</td>
      <td>NaN</td>
      <td>2815.50</td>
      <td>5631.00</td>
      <td>C</td>
      <td>1903</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>PAGAMENTO NF.18837 CHEIM JORDE E ABELHA RODRIG...</td>
      <td>2815.50</td>
      <td>NaN</td>
      <td>2815.50</td>
      <td>C</td>
      <td>F.188</td>
    </tr>
    <tr>
      <th>9</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>NOTA FISCAL 711 RESTAURANTE PRAIA DO SUA LTDA</td>
      <td>NaN</td>
      <td>296.11</td>
      <td>3111.61</td>
      <td>C</td>
      <td>711</td>
    </tr>
    <tr>
      <th>10</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>NOTA FISCAL 711 RESTAURANTE PRAIA DO SUA LTDA</td>
      <td>296.11</td>
      <td>NaN</td>
      <td>2815.50</td>
      <td>C</td>
      <td>711</td>
    </tr>
    <tr>
      <th>11</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>NOTA FISCAL 19214 CHEIM JORGE &amp; ABELHA RODRIGU...</td>
      <td>NaN</td>
      <td>2815.50</td>
      <td>5631.00</td>
      <td>C</td>
      <td>1921</td>
    </tr>
    <tr>
      <th>12</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>PAGAMENTO NF.19032 CHEIM JORGE E ABELHA RODRIG...</td>
      <td>2815.50</td>
      <td>NaN</td>
      <td>2815.50</td>
      <td>C</td>
      <td>F.190</td>
    </tr>
    <tr>
      <th>13</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>NOTA FISCAL 719 RESTAURANTE PRAIA DO SUA LTDA ME</td>
      <td>NaN</td>
      <td>333.63</td>
      <td>3149.13</td>
      <td>C</td>
      <td>719</td>
    </tr>
    <tr>
      <th>14</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>NOTA FISCAL 19421 CHEIM JORGE &amp; ABELHA RODRIGU...</td>
      <td>NaN</td>
      <td>2815.50</td>
      <td>5964.63</td>
      <td>C</td>
      <td>1942</td>
    </tr>
    <tr>
      <th>15</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>PAGAMENTO NF.719 RESTAURANTE PRAIA DO SUA LTDA ME</td>
      <td>333.63</td>
      <td>NaN</td>
      <td>5631.00</td>
      <td>C</td>
      <td>F.719</td>
    </tr>
    <tr>
      <th>16</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>PAGAMENTO NF.19214 CHEIM JORGE &amp; ABELHA RODRIG...</td>
      <td>2815.50</td>
      <td>NaN</td>
      <td>2815.50</td>
      <td>C</td>
      <td>F.192</td>
    </tr>
    <tr>
      <th>17</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>NOTA FISCAL 726 RESTAURANTE PRAIA DO SUA LTDA ME</td>
      <td>NaN</td>
      <td>325.48</td>
      <td>3140.98</td>
      <td>C</td>
      <td>726</td>
    </tr>
    <tr>
      <th>18</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>NOTA FISCAL 19624 CHEIM JORGE &amp; ABELHA RODRIGU...</td>
      <td>NaN</td>
      <td>2815.50</td>
      <td>5956.48</td>
      <td>C</td>
      <td>1962</td>
    </tr>
    <tr>
      <th>19</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>PAGAMENTO NF.19421 CHEIM JORGE &amp; ABELHA RODRIG...</td>
      <td>2815.50</td>
      <td>NaN</td>
      <td>3140.98</td>
      <td>C</td>
      <td>F.194</td>
    </tr>
    <tr>
      <th>20</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>NOTA FISCAL 73 CONSTRUTORA SANTA CLARA LTDA ME</td>
      <td>NaN</td>
      <td>4514.40</td>
      <td>7655.38</td>
      <td>C</td>
      <td>73 C</td>
    </tr>
    <tr>
      <th>21</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>PAGAMENTO NF.73 CONSTRUTORA SANTA CLARA LTDA ME</td>
      <td>4514.40</td>
      <td>NaN</td>
      <td>3140.98</td>
      <td>C</td>
      <td>F.73</td>
    </tr>
    <tr>
      <th>22</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>PAGAMENTO NF.726 RESTAURANTE PRAIA DO SUA LTDA ME</td>
      <td>325.48</td>
      <td>NaN</td>
      <td>2815.50</td>
      <td>C</td>
      <td>F.726</td>
    </tr>
    <tr>
      <th>23</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>PAGAMENTO NF.730 RESTAURANTE PRAIA DO SUA LTDA ME</td>
      <td>NaN</td>
      <td>346.14</td>
      <td>3161.64</td>
      <td>C</td>
      <td>F.730</td>
    </tr>
    <tr>
      <th>24</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>NOTA FISCAL 4697 TERRATEK TECNOLOGIA LTDA</td>
      <td>NaN</td>
      <td>14452.90</td>
      <td>17614.54</td>
      <td>C</td>
      <td>4697</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>52</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>NOTA FISCAL 257 EPG ENGENHARIA LTDA - EPP</td>
      <td>NaN</td>
      <td>3754.00</td>
      <td>3754.00</td>
      <td>C</td>
      <td>257</td>
    </tr>
    <tr>
      <th>53</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>PAGAMENTO NF.257 EPG ENGENHARIA LTDA - EPP</td>
      <td>3754.00</td>
      <td>NaN</td>
      <td>0.00</td>
      <td>D</td>
      <td>F.257</td>
    </tr>
    <tr>
      <th>54</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>VR REF.FATURA 26154 PASSAGENS DNA TURISMO LTDA...</td>
      <td>NaN</td>
      <td>768.52</td>
      <td>768.52</td>
      <td>C</td>
      <td>RA 26</td>
    </tr>
    <tr>
      <th>55</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>PAGAMENTO NF.FATURA 26154 PASSAGENS DNA TURISM...</td>
      <td>768.52</td>
      <td>NaN</td>
      <td>0.00</td>
      <td>D</td>
      <td>F.FAT</td>
    </tr>
    <tr>
      <th>56</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>NOTA FISCAL 759 RESTAURANTE PRAIA DO SUA LTDA ME</td>
      <td>NaN</td>
      <td>351.88</td>
      <td>351.88</td>
      <td>C</td>
      <td>759</td>
    </tr>
    <tr>
      <th>57</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Cheque emitido 610 banco BANCO DO ESTADO D...</td>
      <td>351.88</td>
      <td>NaN</td>
      <td>0.00</td>
      <td>D</td>
      <td>emiti</td>
    </tr>
    <tr>
      <th>58</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>NOTA FISCAL 764 RESTAURANTE PRAIA DO SUA LTDA ...</td>
      <td>NaN</td>
      <td>316.56</td>
      <td>316.56</td>
      <td>C</td>
      <td>764</td>
    </tr>
    <tr>
      <th>59</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>NOTA FISCAL 15 R EDUARDO DA SILVA SERVIÇOS E C...</td>
      <td>NaN</td>
      <td>11270.00</td>
      <td>11586.56</td>
      <td>C</td>
      <td>15 R</td>
    </tr>
    <tr>
      <th>60</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Título 46286 de Marcielle Gomes Torezoni r...</td>
      <td>NaN</td>
      <td>50.00</td>
      <td>11636.56</td>
      <td>C</td>
      <td>46286</td>
    </tr>
    <tr>
      <th>61</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Pagamento do título 46278/1 de Restaurante...</td>
      <td>316.56</td>
      <td>NaN</td>
      <td>11320.00</td>
      <td>C</td>
      <td>46278</td>
    </tr>
    <tr>
      <th>62</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Título 46283 de VPJudice Engenharia Projet...</td>
      <td>NaN</td>
      <td>42000.00</td>
      <td>53320.00</td>
      <td>C</td>
      <td>46283</td>
    </tr>
    <tr>
      <th>63</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Pagamento do título 46266/1 de R Eduardo d...</td>
      <td>11270.00</td>
      <td>NaN</td>
      <td>42050.00</td>
      <td>C</td>
      <td>46266</td>
    </tr>
    <tr>
      <th>64</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Abatimento de adiantamento de Maxima Gestã...</td>
      <td>6000.00</td>
      <td>NaN</td>
      <td>36050.00</td>
      <td>C</td>
      <td>46279</td>
    </tr>
    <tr>
      <th>65</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Título 46279 de Maxima Gestão de Empreendi...</td>
      <td>NaN</td>
      <td>6000.00</td>
      <td>42050.00</td>
      <td>C</td>
      <td>46279</td>
    </tr>
    <tr>
      <th>66</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Pagamento do título 46283/1 de VPJudice En...</td>
      <td>42000.00</td>
      <td>NaN</td>
      <td>50.00</td>
      <td>C</td>
      <td>46283</td>
    </tr>
    <tr>
      <th>67</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Pagamento do título 46286/1 de Marcielle G...</td>
      <td>50.00</td>
      <td>NaN</td>
      <td>0.00</td>
      <td>-</td>
      <td>46286</td>
    </tr>
    <tr>
      <th>68</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Título 46264 de Restaurante Praia do Sua  ...</td>
      <td>NaN</td>
      <td>335.00</td>
      <td>335.00</td>
      <td>C</td>
      <td>46264</td>
    </tr>
    <tr>
      <th>69</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Pagamento do título 46264/1 de Restaurante...</td>
      <td>335.00</td>
      <td>NaN</td>
      <td>0.00</td>
      <td>-</td>
      <td>46264</td>
    </tr>
    <tr>
      <th>70</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Título 46410 de Areia Branca Engenharia Lt...</td>
      <td>NaN</td>
      <td>18667.64</td>
      <td>18667.64</td>
      <td>C</td>
      <td>46410</td>
    </tr>
    <tr>
      <th>71</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Pagamento do título 46410/1 de Areia Branc...</td>
      <td>18667.64</td>
      <td>NaN</td>
      <td>0.00</td>
      <td>-</td>
      <td>46410</td>
    </tr>
    <tr>
      <th>72</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Título 46725 de Restaurante Praia do Sua  ...</td>
      <td>NaN</td>
      <td>315.20</td>
      <td>315.20</td>
      <td>C</td>
      <td>46725</td>
    </tr>
    <tr>
      <th>73</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Título 47105 de VPJudice Engenharia Projet...</td>
      <td>NaN</td>
      <td>78000.00</td>
      <td>78315.20</td>
      <td>C</td>
      <td>47105</td>
    </tr>
    <tr>
      <th>74</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Pagamento do título 46725/1 de Restaurante...</td>
      <td>315.20</td>
      <td>NaN</td>
      <td>78000.00</td>
      <td>C</td>
      <td>46725</td>
    </tr>
    <tr>
      <th>75</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Pagamento do título 47105/1 de VPJudice En...</td>
      <td>78000.00</td>
      <td>NaN</td>
      <td>0.00</td>
      <td>-</td>
      <td>47105</td>
    </tr>
    <tr>
      <th>76</th>
      <td>0     0    2018-01-02\n1    2018-01-05\n2    2...</td>
      <td>Vr. Título 47279 de Restaurante Praia do Sua r...</td>
      <td>NaN</td>
      <td>213.70</td>
      <td>213.70</td>
      <td>C</td>
      <td>47279</td>
    </tr>
  </tbody>
</table>
<p>77 rows × 7 columns</p>
</div>