In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime

###datos del razon contable

In [49]:
razao=pd.DataFrame(pd.read_excel('X:/fabiana 03-04-2020/razao01.xlsx'))
razao['Data']=pd.to_datetime(razao['Data'])
razao['Débito']=pd.to_numeric(razao['Débito'])
razao['Crédito']=pd.to_numeric(razao['Crédito'])
razao['Titulo']=pd.to_numeric(razao['Titulo'])
razao['Débito']=razao['Débito'].replace({np.nan:0.00})
razao['Crédito']=razao['Crédito'].replace({np.nan:0.00})
razao['Saldo']=razao['Crédito']-razao['Débito']
razao

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Data</th>
      <th>Histórico</th>
      <th>Débito</th>
      <th>Crédito</th>
      <th>Titulo</th>
      <th>Saldo</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2019-01-10</td>
      <td>Entrada do titulo 1938 ref.a REC 102019 de MAR...</td>
      <td>0.00</td>
      <td>165.56</td>
      <td>1938</td>
      <td>165.56</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2019-01-10</td>
      <td>Entrada do titulo 1947 ref.a NFSE 188 de DE MA...</td>
      <td>0.00</td>
      <td>11741.50</td>
      <td>1947</td>
      <td>11741.50</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2019-01-10</td>
      <td>Entrada do titulo 2024 ref.a NFE 3015 de PADAR...</td>
      <td>0.00</td>
      <td>540.00</td>
      <td>2024</td>
      <td>540.00</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2019-01-10</td>
      <td>Entrada do titulo 2025 ref.a NFSE 5598 de LOCA...</td>
      <td>0.00</td>
      <td>3042.00</td>
      <td>2025</td>
      <td>3042.00</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2019-03-10</td>
      <td>Entrada do titulo 1983 ref.a NFSE 33105976 de ...</td>
      <td>0.00</td>
      <td>463.80</td>
      <td>1983</td>
      <td>463.80</td>
    </tr>
    <tr>
      <th>5</th>
      <td>2019-03-10</td>
      <td>Entrada do titulo 2051 ref.a NFE 39480 de POLI...</td>
      <td>0.00</td>
      <td>640.00</td>
      <td>2051</td>
      <td>640.00</td>
    </tr>
    <tr>
      <th>6</th>
      <td>2019-04-10</td>
      <td>NOTA FISCAL 28363 COPIADORA PHENIX LTDA</td>
      <td>0.00</td>
      <td>222.64</td>
      <td>1985</td>
      <td>222.64</td>
    </tr>
    <tr>
      <th>7</th>
      <td>2019-04-10</td>
      <td>Pagamento do título 1947/1 de DE MARTIN CONSTR...</td>
      <td>11741.50</td>
      <td>0.00</td>
      <td>1947</td>
      <td>-11741.50</td>
    </tr>
    <tr>
      <th>8</th>
      <td>2019-04-10</td>
      <td>Pagamento do título 1925/1 de MARCELO REBLIN D...</td>
      <td>3424.40</td>
      <td>0.00</td>
      <td>1925</td>
      <td>-3424.40</td>
    </tr>
    <tr>
      <th>9</th>
      <td>2019-07-10</td>
      <td>Entrada do titulo 1998 ref.a REC 19007522 de U...</td>
      <td>0.00</td>
      <td>97.60</td>
      <td>1998</td>
      <td>97.60</td>
    </tr>
    <tr>
      <th>10</th>
      <td>2019-07-10</td>
      <td>Pagamento do título 1938/1 de MARCELO REBLIN D...</td>
      <td>165.56</td>
      <td>0.00</td>
      <td>1938</td>
      <td>-165.56</td>
    </tr>
    <tr>
      <th>11</th>
      <td>2019-07-10</td>
      <td>Pagamento do título 1983/1 de TICKET SOLUCOES ...</td>
      <td>463.80</td>
      <td>0.00</td>
      <td>1983</td>
      <td>-463.80</td>
    </tr>
    <tr>
      <th>12</th>
      <td>2019-07-10</td>
      <td>Pagamento do título 1857/1 de A G PROJETOS ref...</td>
      <td>3330.00</td>
      <td>0.00</td>
      <td>1857</td>
      <td>-3330.00</td>
    </tr>
    <tr>
      <th>13</th>
      <td>2019-07-10</td>
      <td>Pagamento do título 1923/1 de CENTRALFER CENTR...</td>
      <td>4640.83</td>
      <td>0.00</td>
      <td>1923</td>
      <td>-4640.83</td>
    </tr>
    <tr>
      <th>14</th>
      <td>2019-07-10</td>
      <td>Pagamento do título 1607/1 de MARCUS VINICIUS ...</td>
      <td>912.00</td>
      <td>0.00</td>
      <td>1607</td>
      <td>-912.00</td>
    </tr>
    <tr>
      <th>15</th>
      <td>2019-07-10</td>
      <td>Pagamento do título 1607/2 de MARCUS VINICIUS ...</td>
      <td>19.00</td>
      <td>0.00</td>
      <td>1607</td>
      <td>-19.00</td>
    </tr>
    <tr>
      <th>16</th>
      <td>2019-07-10</td>
      <td>Pagamento do título 2019/1 de UNIAO MATERIAIS ...</td>
      <td>790.00</td>
      <td>0.00</td>
      <td>2019</td>
      <td>-790.00</td>
    </tr>
    <tr>
      <th>17</th>
      <td>2019-10-10</td>
      <td>Entrada do titulo 2071 ref.a FAT 5610 de LOCSO...</td>
      <td>0.00</td>
      <td>5000.00</td>
      <td>2071</td>
      <td>5000.00</td>
    </tr>
    <tr>
      <th>18</th>
      <td>2019-10-10</td>
      <td>Pagamento do título 1945/2 de ARCELOR MITTAL r...</td>
      <td>11215.82</td>
      <td>0.00</td>
      <td>1945</td>
      <td>-11215.82</td>
    </tr>
    <tr>
      <th>19</th>
      <td>2019-10-10</td>
      <td>Pagamento do título 1922/1 de CENTRALFER CENTR...</td>
      <td>2379.92</td>
      <td>0.00</td>
      <td>1922</td>
      <td>-2379.92</td>
    </tr>
    <tr>
      <th>20</th>
      <td>2019-11-10</td>
      <td>Entrada do titulo 2152 ref.a FAT 8019 de ORGUE...</td>
      <td>0.00</td>
      <td>1687.68</td>
      <td>2152</td>
      <td>1687.68</td>
    </tr>
    <tr>
      <th>21</th>
      <td>2019-11-10</td>
      <td>Entrada do titulo 2153 ref.a FAT 8020 de ORGUE...</td>
      <td>0.00</td>
      <td>5926.42</td>
      <td>2153</td>
      <td>5926.42</td>
    </tr>
    <tr>
      <th>22</th>
      <td>2019-11-10</td>
      <td>Entrada do titulo 2154 ref.a FAT 8021 de ORGUE...</td>
      <td>0.00</td>
      <td>968.98</td>
      <td>2154</td>
      <td>968.98</td>
    </tr>
    <tr>
      <th>23</th>
      <td>2019-12-10</td>
      <td>Entrada do titulo 2296 ref.a NFSE 11172 de CON...</td>
      <td>0.00</td>
      <td>57770.46</td>
      <td>2296</td>
      <td>57770.46</td>
    </tr>
    <tr>
      <th>24</th>
      <td>2019-10-14</td>
      <td>Entrada do titulo 2316 ref.a FAT 035195811 de ...</td>
      <td>0.00</td>
      <td>515.75</td>
      <td>2316</td>
      <td>515.75</td>
    </tr>
    <tr>
      <th>25</th>
      <td>2019-10-14</td>
      <td>Entrada do titulo 2325 ref.a NFE 283893 de ARC...</td>
      <td>0.00</td>
      <td>14933.88</td>
      <td>2325</td>
      <td>14933.88</td>
    </tr>
    <tr>
      <th>26</th>
      <td>2019-10-14</td>
      <td>Entrada do titulo 2328 ref.a NFE 283894 de ARC...</td>
      <td>0.00</td>
      <td>13785.12</td>
      <td>2328</td>
      <td>13785.12</td>
    </tr>
    <tr>
      <th>27</th>
      <td>2019-10-15</td>
      <td>Entrada do titulo 2082 ref.a NFE 14007 de BRAS...</td>
      <td>0.00</td>
      <td>650.00</td>
      <td>2082</td>
      <td>650.00</td>
    </tr>
    <tr>
      <th>28</th>
      <td>2019-10-15</td>
      <td>Entrada do titulo 2184 ref.a NFE 27978 de MEGA...</td>
      <td>0.00</td>
      <td>205.00</td>
      <td>2184</td>
      <td>205.00</td>
    </tr>
    <tr>
      <th>29</th>
      <td>2019-10-15</td>
      <td>Pagamento do título 1985/1 de LUAN COPIADORA r...</td>
      <td>222.64</td>
      <td>0.00</td>
      <td>1985</td>
      <td>-222.64</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>612</th>
      <td>2020-01-27</td>
      <td>Pagamento do título 3319/1 de LOCA EXPRESS ref...</td>
      <td>3522.00</td>
      <td>0.00</td>
      <td>3319</td>
      <td>-3522.00</td>
    </tr>
    <tr>
      <th>613</th>
      <td>2020-01-27</td>
      <td>Pagamento do título 3365/1 de CESAN referente ...</td>
      <td>267.52</td>
      <td>0.00</td>
      <td>3365</td>
      <td>-267.52</td>
    </tr>
    <tr>
      <th>614</th>
      <td>2020-01-27</td>
      <td>Pagamento do título 2457/3 de TRIFEL INDUSTRIA...</td>
      <td>26012.12</td>
      <td>0.00</td>
      <td>2457</td>
      <td>-26012.12</td>
    </tr>
    <tr>
      <th>615</th>
      <td>2020-01-27</td>
      <td>Pagamento do título 3377/1 de COMPROCARD LTDA ...</td>
      <td>2580.00</td>
      <td>0.00</td>
      <td>3377</td>
      <td>-2580.00</td>
    </tr>
    <tr>
      <th>616</th>
      <td>2020-01-27</td>
      <td>Pagamento do título 3098/1 de BRASMETAL (GUARA...</td>
      <td>650.00</td>
      <td>0.00</td>
      <td>3098</td>
      <td>-650.00</td>
    </tr>
    <tr>
      <th>617</th>
      <td>2020-01-27</td>
      <td>Pagamento do título 3375/1 de CONTAGOS referen...</td>
      <td>1039.00</td>
      <td>0.00</td>
      <td>3375</td>
      <td>-1039.00</td>
    </tr>
    <tr>
      <th>618</th>
      <td>2020-01-27</td>
      <td>Pagamento do título 2831/2 de MEGAFER PARAFUSO...</td>
      <td>650.00</td>
      <td>0.00</td>
      <td>2831</td>
      <td>-650.00</td>
    </tr>
    <tr>
      <th>619</th>
      <td>2020-01-27</td>
      <td>Pagamento do título 3257/1 de SINDICIG referen...</td>
      <td>1002.25</td>
      <td>0.00</td>
      <td>3257</td>
      <td>-1002.25</td>
    </tr>
    <tr>
      <th>620</th>
      <td>2020-01-27</td>
      <td>Pagamento do título 3309/1 de MARCELO REBLIN D...</td>
      <td>52.00</td>
      <td>0.00</td>
      <td>3309</td>
      <td>-52.00</td>
    </tr>
    <tr>
      <th>621</th>
      <td>2020-01-27</td>
      <td>Pagamento do título 3348/1 de RICARDO JOSE DE ...</td>
      <td>104.71</td>
      <td>0.00</td>
      <td>3348</td>
      <td>-104.71</td>
    </tr>
    <tr>
      <th>622</th>
      <td>2020-01-27</td>
      <td>Pagamento do título 3344/1 de UNIFORMES E ACES...</td>
      <td>207.20</td>
      <td>0.00</td>
      <td>3344</td>
      <td>-207.20</td>
    </tr>
    <tr>
      <th>623</th>
      <td>2020-01-27</td>
      <td>Pagamento do título 3397/1 de RONALDO DO VALE ...</td>
      <td>359.69</td>
      <td>0.00</td>
      <td>3397</td>
      <td>-359.69</td>
    </tr>
    <tr>
      <th>624</th>
      <td>2020-01-27</td>
      <td>Pagamento do título 3307/1 de AMAURY DE SOUZA ...</td>
      <td>251.42</td>
      <td>0.00</td>
      <td>3307</td>
      <td>-251.42</td>
    </tr>
    <tr>
      <th>625</th>
      <td>2020-01-28</td>
      <td>Pagamento do título 3393/1 de ROMA IMÓVEIS ref...</td>
      <td>4000.00</td>
      <td>0.00</td>
      <td>3393</td>
      <td>-4000.00</td>
    </tr>
    <tr>
      <th>626</th>
      <td>2020-01-28</td>
      <td>Pagamento do título 3522/1 de CESAN referente ...</td>
      <td>610.38</td>
      <td>0.00</td>
      <td>3522</td>
      <td>-610.38</td>
    </tr>
    <tr>
      <th>627</th>
      <td>2020-01-29</td>
      <td>Entrada do titulo 3525 ref.a NFSE 87 de GESSO ...</td>
      <td>0.00</td>
      <td>10192.59</td>
      <td>3525</td>
      <td>10192.59</td>
    </tr>
    <tr>
      <th>628</th>
      <td>2020-01-29</td>
      <td>Entrada do titulo 3529 ref.a FAT 57198887 de S...</td>
      <td>0.00</td>
      <td>410.00</td>
      <td>3529</td>
      <td>410.00</td>
    </tr>
    <tr>
      <th>629</th>
      <td>2020-01-29</td>
      <td>Entrada do titulo 3533 ref.a NFE 2199 de BLESS...</td>
      <td>0.00</td>
      <td>199.97</td>
      <td>3533</td>
      <td>199.97</td>
    </tr>
    <tr>
      <th>630</th>
      <td>2020-01-29</td>
      <td>Entrada do titulo 3550 ref.a NFSE 272 de M.C P...</td>
      <td>0.00</td>
      <td>6680.00</td>
      <td>3550</td>
      <td>6680.00</td>
    </tr>
    <tr>
      <th>631</th>
      <td>2020-01-29</td>
      <td>Entrada do titulo 3603 ref.a FAT 7419270 de SÃ...</td>
      <td>0.00</td>
      <td>66.63</td>
      <td>3603</td>
      <td>66.63</td>
    </tr>
    <tr>
      <th>632</th>
      <td>2020-01-30</td>
      <td>Entrada do titulo 3541 ref.a REC 012020 de ELI...</td>
      <td>0.00</td>
      <td>44.00</td>
      <td>3541</td>
      <td>44.00</td>
    </tr>
    <tr>
      <th>633</th>
      <td>2020-01-30</td>
      <td>Entrada do titulo 3543 ref.a REC 012020 de MAR...</td>
      <td>0.00</td>
      <td>198.89</td>
      <td>3543</td>
      <td>198.89</td>
    </tr>
    <tr>
      <th>634</th>
      <td>2020-01-30</td>
      <td>Entrada do titulo 3584 ref.a NFE 521 de PERSIA...</td>
      <td>0.00</td>
      <td>4500.00</td>
      <td>3584</td>
      <td>4500.00</td>
    </tr>
    <tr>
      <th>635</th>
      <td>2020-01-30</td>
      <td>Entrada do titulo 3586 ref.a NFE 9652 de DEPOS...</td>
      <td>0.00</td>
      <td>750.00</td>
      <td>3586</td>
      <td>750.00</td>
    </tr>
    <tr>
      <th>636</th>
      <td>2020-01-31</td>
      <td>Entrada do titulo 3583 ref.a NFE 107220 de DOC...</td>
      <td>0.00</td>
      <td>636.00</td>
      <td>3583</td>
      <td>636.00</td>
    </tr>
    <tr>
      <th>637</th>
      <td>2020-01-31</td>
      <td>Entrada do titulo 3587 ref.a NFE 17238 de SALV...</td>
      <td>0.00</td>
      <td>3291.76</td>
      <td>3587</td>
      <td>3291.76</td>
    </tr>
    <tr>
      <th>638</th>
      <td>2020-01-31</td>
      <td>Entrada do titulo 3607 ref.a NFE 22934 de STYL...</td>
      <td>0.00</td>
      <td>621.30</td>
      <td>3607</td>
      <td>621.30</td>
    </tr>
    <tr>
      <th>639</th>
      <td>2020-01-31</td>
      <td>Entrada do titulo 3608 ref.a NFE 19537 de DISM...</td>
      <td>0.00</td>
      <td>1143.00</td>
      <td>3608</td>
      <td>1143.00</td>
    </tr>
    <tr>
      <th>640</th>
      <td>2020-01-31</td>
      <td>Entrada do titulo 3627 ref.a NFSE 11548 de CON...</td>
      <td>0.00</td>
      <td>5163.84</td>
      <td>3627</td>
      <td>5163.84</td>
    </tr>
    <tr>
      <th>641</th>
      <td>2020-01-31</td>
      <td>Entrada do titulo 3628 ref.a NFSE 11549 de CON...</td>
      <td>0.00</td>
      <td>57503.25</td>
      <td>3628</td>
      <td>57503.25</td>
    </tr>
  </tbody>
</table>
<p>642 rows × 6 columns</p>
</div>

In [50]:
razao['Crédito'].sum()-razao['Débito'].sum()

440211.3700000001

###datos de los titulos

In [51]:
titulo=pd.DataFrame(pd.read_excel('X:/fabiana 03-04-2020/titulos01.xlsx'))
titulo['Dt emissão']=pd.to_datetime(titulo['Dt emissão'])
titulo['Dt vecto']=pd.to_datetime(titulo['Dt vecto'])
titulo['Dt baixa']=pd.to_datetime(titulo['Dt baixa'])
titulo['Titulo']=pd.to_numeric(titulo['Titulo'])
titulo['Valor original']=pd.to_numeric(titulo['Valor original'])
titulo['Valor da baixa']=pd.to_numeric(titulo['Valor da baixa'])

In [52]:
datos=pd.DataFrame(pd.merge(razao,titulo,on='Titulo'))

In [53]:
datos.dtypes

Data              datetime64[ns]
Histórico                 object
Débito                   float64
Crédito                  float64
Titulo                     int64
Saldo                    float64
Documento                 object
Parcela                   object
Dt emissão        datetime64[ns]
Valor original           float64
Dt vecto          datetime64[ns]
Dt baixa          datetime64[ns]
Valor da baixa           float64
Credor                    object
dtype: object

In [54]:
datos_fin=datos[['Data','Credor','Histórico','Débito','Crédito','Saldo','Titulo',
'Documento','Parcela']]
datos_fin=pd.DataFrame(datos_fin)

In [55]:
datos_fin=datos_fin.set_index('Titulo')

In [57]:
relatorio_01=pd.DataFrame(datos_fin.groupby(['Credor','Titulo'])[['Débito','Crédito','Saldo']].sum())
relatorio_01.to_excel('X:/fabiana 03-04-2020/relatorio_01.xlsx')

In [58]:
relatorio_02=pd.DataFrame(datos_fin.groupby(['Credor'])[['Débito','Crédito','Saldo']].sum())
relatorio_02.to_excel('X:/fabiana 03-04-2020/relatorio_02.xlsx')

In [59]:
relatorio_03=pd.DataFrame(datos_fin.groupby(['Credor','Titulo','Documento'])[['Débito','Crédito','Saldo']].sum())
relatorio_03.to_excel('X:/fabiana 03-04-2020/relatorio_03.xlsx')

In [60]:
relatorio_04=pd.DataFrame(datos_fin.groupby(['Credor','Titulo','Data'])[['Débito','Crédito','Saldo']].sum())
relatorio_04.to_excel('X:/fabiana 03-04-2020/relatorio_04.xlsx')

PermissionError: [Errno 13] Permission denied: 'X:/fabiana 03-04-2020/relatorio_04.xlsx'